### ISSUE TITLE
Re-factor `commit-message.yml` workflow to reuse Slicer workflow

### ISSUE THREAD

**Issue by jcfr** [KitwareMedical/SlicerCustomAppTemplate#65]
After the integration of Slicer pull-request https://github.com/Slicer/Slicer/pull/7898, refactor the existing `commit-message.yml` workflows to leverage the reusable workflow. 

The existing workflow should be updated to use a syntax similar to the following:

```yml
jobs:
   check-commit-message:
     uses: Slicer/Slicer/.github/workflows/commit-message.yml@<SHA>
```

Replace `<SHA>` with the appropriate commit hash corresponding to the merged pull request.
